### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by furandose** [yiffparty/tracker#6]
I've recently noticed few creators that have corrupted files in their posts. I don't know how vast this problem is but I saw it in both new and old creators. Errors happened to zips, pngs, jpgs however I didn't find out if it's only CUF problem or it affects all creators.

Example:
![350err](https://cloud.githubusercontent.com/assets/28780543/26451087/c9841dd8-415a-11e7-8c49-83a6c0f848f9.png)

**Comment by kubotah** [comment]
The underlying issue has been fixed. Some attachments were returning 403 errors when being downloaded, presumably because the creator removed the patron during the process. The scraper will now check to see if attachment download returns an error, if so, the relevant post will be skipped, and it can be rechecked in a future update cycle.

As for attachments already affected, we will now work on re-fetching those that we can, but CUF attachments will need to be re-fetched via the importer.

**Comment by kubotah** [comment]
We've taken the decision of simply removing all affected attachments' posts (~1000), so that they can be re-fetched again. 80% of the posts were from a single creator so the impact is not that bad.
