### ISSUE TITLE
ability to categorizing artists into multiple categories 

### ISSUE THREAD

**Issue by woebbi** [yiffparty/tracker#9]
would be cool to if we could be able to categorizing artists into multiple categories

**Comment by kubotah** [comment]
But that then begs the question of how many categories a creator should be allowed into. The reason you can only vote for one right now is because the category with the most votes is the one applied to the creator - or, if there's a tie, it would be multiple categories.

It would cause problems if we allowed multiple categories. Say I increased the limit to 2. A creator with 10 votes for Furry and 2 votes for Human would end up in both categories, which would cause a lot of confusion for the people who voted Furry.

**Comment by woebbi** [comment]
fair enough, thanks
